### ISSUE TITLE
<SvelteEditor> is not a valid SSR component

### ISSUE THREAD

**Issue by digitaldrreamer** [lynhan318/nextlint#91]
Hey there 👋

Firstly, nice job on this project. It's exactly what I've needed for a long time🫂.

I keep getting this error and I'm confused. Usually, I'd switch dependencies, but nextlint is too good to pass on😊. 

`Error: <SvelteEditor> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <SvelteEditor>.`

I'm kind of confused 🥲 and I haven't gotten any real closure on this. I've gotten this with some dependencies in the past using svelte(kit) + vite, and I haven't been able to go forward without switching dependencies.

I hope I can get some help here, and perhaps some background (down-to-earth) info on what exactly causes this error using svelte(kit) + vite. Thanks in advance!

**Comment by digitaldrreamer** [comment]
Yes actually.

I actually found a workaround yesterday and should have updated this issue. My bad ☺️

Thanks for the prompt response and great work

**Comment by lynhan318** [comment]
Cool @digitaldrreamer.

**Comment by digitaldrreamer** [comment]
Hello again @lynhan318 

We switched to tinymce on that project.

Now I'm back and trying to use nextlint on my own project. But I keep getting this same error.
I can't seem to remember the fix since I deleted the branch for it after being told we'll switch to tinymce :( 

Here's my code, after hours of (unsuccessful) debugging:
```svelte
<script>
	import { browser } from '$app/environment';
	import { onMount } from 'svelte';
	export let value = '';
	let editor;
	let EditorTheme;
	let SvelteEditor;
	let loaded = false;
	onMount(async () => {
		const { EditorTheme: editorTheme } = await import('@nextlint/svelte/EditorTheme');
		const { SvelteEditor: svelteEditor } = await import('@nextlint/svelte');
		EditorTheme = editorTheme;
		SvelteEditor = svelteEditor;
		loaded = true;
	});
</script>

{#if browser && loaded}
	<p>Hello World</p>
	<div class="editor">
		<EditorTheme>
			<SvelteEditor
				onChange={(_editor) => {
					editor = _editor;
					value = _editor.getJSON().text ?? '';
				}}
				onCreated={(_editor) => {
					editor = _editor;
				}}
				content=""
				placeholder="Start editing..."
			/>
		</EditorTheme>
	</div>
{/if}
```


I've also tried this.
```svelte
<script>
    import {SvelteEditor} from '@nextlint/svelte';
    import EditorTheme from '@nextlint/svelte/EditorTheme';
  </script>
  
  <div class="editor">
    <EditorTheme>
      <SvelteEditor content="" placeholder="Start editing..." />
    </EditorTheme>
  </div>
```

I keep getting a 500. Help would be greatly appreciated.
Running on SvelteKit, svelte 4.2.7, @nextlint/svelte v3.1.0
